[project]
name = "coral-interface-agent"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "langchain==0.3.24",
    "langchain-community==0.3.23",
    "langchain-mcp-adapters==0.0.10",
    "langchain-openai==0.3.19",
]
